# Generated by Django 2.1.4 on 2019-01-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=20)),
                ('movie_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('year', models.DateField()),
                ('poster', models.ImageField(upload_to='')),
                ('trailer', models.FileField(upload_to='video/')),
                ('cast', models.ManyToManyField(to='cinema.Actors')),
                ('category', models.ManyToManyField(to='cinema.Category')),
            ],
        ),
        migrations.AddField(
            model_name='likes',
            name='like_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Movies'),
        ),
    ]
