# Generated by Django 2.1.4 on 2019-01-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='photo',
            field=models.ImageField(default=20, upload_to='photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='trailer',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
