# Generated by Django 2.1.4 on 2019-01-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20190106_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Movies')),
            ],
        ),
    ]
