# Generated by Django 2.1.4 on 2019-01-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(default=52, max_length=200),
            preserve_default=False,
        ),
    ]
